### ISSUE TITLE
リファクタ：toAbsoluteUrl()で、呼び出される毎にエレメントを生成する必要はない

### ISSUE THREAD

**Issue by fukudayasuo** [hifive/hifivemain#384]
toAbsoltueUrl()は、a要素のhref属性に相対パスを設定して、a要素のhrefの値を取得することで絶対パスを取得している。

現状の実装だとtoAbsoluteUrl()の呼び出しごとに要素を生成しているが、その必要はない。パフォーマンスのために同じa要素を使用するようにする。

**Comment by fukudayasuo** [comment]
IE7以下で、setAttribute()でhrefを指定しても、取得するときに絶対パスにならず、絶対パスを取得できない。
innerHTMLやinsertAdjacentHTMLを使う方法を検討する。
参考 http://qiita.com/sounisi5011/items/e24d0e1dfd71c5dd528e

**Comment by simdy** [comment]
@fukudayasuo 
History APIによりブラウザのヒストリを書き換えた場合に正しく解決できるか確認をお願いします。

期待される結果：
（初期状態）ブラウザアドレスバーのURL： /init/path/index.html
toAbsoluteUrl('../path2/file2.html') -> /init/path2/file2.html
History APIにてURLを以下に書き換える： /changed/path3/to/file3.html
toAbsoluteUrl('../file4.html') -> /changed/path3/file4.html

**Comment by fukudayasuo** [comment]
History APIでブラウザヒストリを書き換えた場合も、書き換えた後のアドレスが元になって上記のように動作することを確認しました。
