### ISSUE TITLE
リゾルバ配列を公開する

### ISSUE THREAD

**Issue by fukudayasuo** [hifive/hifivemain#386]
関連 #373 
リゾルバ配列を外部に公開し、リゾルバの順序や追加、削除、修正を外部から行えるようにする。

公開する配列は、以下のようなtypeとresolverを持つオブジェクトの配列にする。

```javascript
[{ type: 'namespace', resolver: function(){...}, ...]
```

**Comment by simdy** [comment]
リゾルバの追加・削除は次のバージョンで対応することとします。
