### ISSUE TITLE
シーン遷移機能・メインシーンコンテナでの遷移時の、シーン間パラメータのURL保存方式の検討

### ISSUE THREAD

**Issue by tossuzuki** [hifive/hifivemain#428]
・h5.u.obj.serialize、h5.u.obj.deserializeを使用する想定。
・クエリパラメータを使用する場合、サーバーサイドで使用するものとの併存について考慮する必要がある。
  (パラメータ名のプレフィクス等)
・クエリパラメータではなくハッシュを使う方式も提供するか。
・パラメータのサイズ制限はどうするか。
・シーン遷移時にURLにパラメーターを保持しない方式の提供(履歴遷移時は「再表示不可」等の画面を表示)

**Comment by tossuzuki** [comment]
関連コミット
メインシーンコンテナのシーン間パラメーターをURLに保持するよう実装
メインシーンコンテナの遷移先にコントローラーを指定できるよう実装
f487c2a170f46dc580f857e6941582fdcc06e54c
ハッシュによる遷移対応
e2efe94679d621ebd45018ec895e1a32b69aeb15

残件は
・シーン遷移時にURLにパラメーターを保持しない方式の提供(履歴遷移時は「再表示不可」等の画面を表示)

**Comment by fukudayasuo** [comment]
再表示不可画面について

``h5.settings.scene.notReshowable`` にコントローラ定義オブジェクトを指定すると、そのコントローラが再表示不可画面にバインドされます。
また、``h5.settings.scene.notReshowableMessage``に指定したメッセージは、再表示不可画面にバインドされるコントローラのコントローラバインド時の引数として使用されます。コントローラ引数は以下のようなオブジェクトです。
```
{
  _notReshowableMessage: /* 設定したメッセージ */
}
```

デフォルトでは、再表示不可画面では設定したメッセージ(デフォルトでは"この画面は再表示できません。")をh1要素でシーンに表示するコントローラが適用されます。
