### ISSUE TITLE
Router機能の実装

### ISSUE THREAD

**Issue by tossuzuki** [hifive/hifivemain#441]

**Comment by tossuzuki** [comment]
シーン機能側の実装追加を、間違って別のコミットに入れてしまったので、こちらに追記します。
1fe4fb2ea494a9807ebe40563920670ceacef71a
修正点：
・シーン機能のルーティングルールのtestで、関数の場合
  ・第二仮引数にurlをオブジェクト化したものを追加
・シーン機能のルーティングルールのnavigationInfoで、関数を指定できるようにする
  ・第一仮引数にurl、第二仮引数にurlをオブジェクト化したものを設定
  ・ルーティング先のnavigationInfoを返却する
  ・nullを返却すると、元のurlの画面を表示する

**Comment by simdy** [comment]
Router自体はver.1.2.0では内部で使用する機能として実装しています。
（sceneモジュールが使用）
外部への公開は今後検討します。
