### ISSUE TITLE
シーン機能：メインシーンコンテナ遷移時のブラウザヘッダタイトルの追従

### ISSUE THREAD

**Issue by tossuzuki** [hifive/hifivemain#448]
現状、メインシーンコンテナのシーン遷移時にはブラウザ上部のタイトルは変更していない。
遷移に追従して変更する場合は、以下の方式が考えられる。

・navigate()で引数指定されたら強制的にそれにする
・遷移先がHTMLの場合 (以下、先の条件が優先)
　 ・シーン要素のdata-title属性があればこれを使用する
　　※遷移時だけでなく初期表示(直接アクセス、リロード)時にも対応すること。
　・&lt;tiltle&gt;タグ内容
　・以上の該当がなければ変更しない
　※メインシーンコンテナ内に複数シーン(v1.2.1では未対応)がある場合も考慮する。
・遷移先がControllerの場合
　・シーンコントローラ側で特定のプロパティでタイトルを指定しておいてもらう
　・なければ変更しない
・追従するかどうかのデフォルト設定はsettingsで設定可能に

**Comment by fukudayasuo** [comment]
メインシーンコンテナでの遷移時のタイトル追従機能実装しました。

タイトル追従を行うかどうかは、 h5.settings.scene.followTitleで指定(デフォルトはtrue)
タイトルは以下のように決定されます。
* navigate()やchangeScene()で指定されたパラメータのtitleプロパティの値
* toにコントローラ名が指定された場合はそのコントローラのsceneTitleプロパティの値
* toにページURLが指定された場合は以下
 * シーン要素のdata-title属性の値
 * シーン要素内のtitleタグの内容

いずれにも該当しない場合は現在のタイトルからの変更を行いません。
