### ISSUE TITLE
ControllerとLogicのライフサイクルメソッドを定義するプロパティ（__readyなど）のDocを記述する

### ISSUE THREAD

**Issue by simdy** [hifive/hifivemain#478]
ControllerとLogicのAPIDocに、それぞれがサポートするライフサイクルメソッドのプロパティを記述する。
Membersとして記述。

なお、ライフサイクルメソッドを指定することはオプションであり
記述しなくても動作する旨記述すること。

**Comment by fukudayasuo** [comment]
c57f1c1de67eb8946d570c086f00dddbb9ca2dad 
コントローラ及びロジックのライフサイクルメソッドのJSDoc記述しました。
