### ISSUE TITLE
Dependency.resolve()の引数typeの削除

### ISSUE THREAD

**Issue by simdy** [hifive/hifivemain#482]
typeプロパティは削除する。

**Comment by fukudayasuo** [comment]
リソースの解決においてtype指定の無い場合、どのリゾルバを使うかはリソースキーのみで判定するようになります。

# 例えば、リソースキーが"app.hoge.ejs"は必ずテンプレートリゾルバ、"template"は必ず名前空間になるなど。

899cc2de5c5bf6ed9bfcd8ea8baad85c37989e1d
で、その制約を取り入れることは一旦無しとしました。(元に戻しました)
