### ISSUE TITLE
SceneContainerController.changeScene()のメソッド名をnavigate()にする

### ISSUE THREAD

**Issue by simdy** [hifive/hifivemain#483]
#479 に合わせ、メソッド名をnavigate()にする。

**Comment by fukudayasuo** [comment]
26c91ba25a6d099fffaf40e3fccd318a29ba8854
#452 で対応済みでしたが、前のtriggerChangeSceneのJSDocが残っていたため削除しました。

**Comment by fukudayasuo** [comment]
#452 ではSceneContainerController.changeScene()のメソッド名は変更していませんでした。
293354b04f8c7145b8f7f9b739019c28042b7ef5 で対応しました。
