### ISSUE TITLE
Controller.disableListeners()で、on()を使ってバインドしたハンドラを無効にできない

### ISSUE THREAD

**Issue by fukudayasuo** [hifive/hifivemain#489]
以下のコードで確認した。
```
var c = h5.core.controller('body', {
  __name:'test1'
});
c.readyPromise.done(function(){
  c.on('{rootElement}', 'click', function(){
    console.log('clicked');
  });
  c.trigger('click');   // -> 'click'
  c.disableListeners();
  c.trigger('click');  // -> 'click'
});
```

**Comment by fukudayasuo** [comment]
## on()でバインドした動的ハンドラの名前について ##
コントローラ及びロジックのメソッドにはアスペクトを設定することができます。この時に``pointCut``プロパティでメソッド名にマッチするかどうかの設定を記述できます。

**on()で動的にバインドしたハンドラは、関数名無し扱いとし、任意の``pointCut``にマッチしません。つまり``pointCut``をどう書いても動的バインドしたハンドラを対象にインターセプタを掛けることはできません。**

```javascript
h5.settings.aspects = [{
  target: 'app.controller.SampleController',
  interceptors: h5.core.interceptor.lap,
  pointCut: /.*/
}];
// app.controller.SampleControllerに動的に追加されたハンドラは対象にならない
```

動的バインドしたハンドラを対象にしたい場合は``pointCut``を定義せずにアスペクト設定を記述してください。

```javascript
h5.settings.aspects = [{
  target: 'app.controller.SampleController',
  interceptors: h5.core.interceptor.lap
}];
// app.controller.SampleControllerに動的に追加されたハンドラも対象になる
```

この仕様は、動的イベントハンドラは、静的イベントハンドラと違い、セレクタとイベント名のセットを重複して記述できるため、セレクタ名とイベント名から仮の名前を付けたところでハンドラを特定できないためです。

```javascript
h5.core.controller('body',{
  __name: 'app.SampleController',
  __ready: function(){
    this.on('{rootElement}', 'click', handler1);
    this.on('{rootElement}', 'click', handler2);
  },
  '{rootElement} click': handler3
});

// 上記の場合、pointCutで'{rootElment} click'を指定した場合は、
// 元々定義されているhandler3のみが対象
```

**また、インターセプタに渡される``invocation``の``invocation.funcName``には空文字をセットしています。**

これも同様の理由で、仮の名前を付けても``invocation.target``と``invocation.funcName``からハンドラを特定できないためです。

**Comment by simdy** [comment]
eff90a8 により、on()でバインドした関数の関数名は常に空文字となります。
従って、アスペクト設定時に空文字がマッチするpointCut or ポイントカット指定なし　なら
on()でバインドした動的なイベントハンドラにもアスペクトがかかります。
