### ISSUE TITLE
非同期バリデート時のValidationResult.isValidが結果がまだ出ていない時にnullではなくtrueになっている

### ISSUE THREAD

**Issue by fukudayasuo** [hifive/hifivemain#503]
結果待ち中の場合はisValidはnullにする

**Comment by fukudayasuo** [comment]
元々、isValidは現在validな状態かどうか（結果待ちがあるならtrue、結果が待ちが無いなら今までのvalid結果)を表すフラグでした。

isAllValidが結果がまだ出ていないならnull、今までの結果でvalidでないならfalse、という扱いでした。

この挙動になるように、isValidにnullを持たせるようにした部分は元に戻しました。

また、isAllValidの判定や判定タイミングに問題があったため、コードを修正しました。

**Comment by simdy** [comment]
isValidは「現在までのバリデーション結果」を表し、isAllValidは「（非同期を含む）すべてのバリデーション結果」を表します。

非同期バリデーションを含まない場合はisValidとisAllValidは同じ値になります。
非同期バリデーションを含む場合、
同期的なチェックですでにエラーがある場合は`isValid==isAllValid==false`となり、
エラーがない場合は、
非同期チェックの結果でfalseなものがまだない⇒`isValid==true, isAllValid==null`
falseなものが一つでも帰ってきたら⇒`isValid==isAllValid==false`
となります。
