### ISSUE TITLE
h5.scene: createSceneContainer()でシーンコンテナを生成した時、シーン要素のdata-titleがシーンコンテナのタイトルに設定されない

### ISSUE THREAD

**Issue by tom75s** [hifive/hifivemain#513]
createSceneContainer()でシーンコンテナを生成した時、シーン要素のdata-titleがタイトルに設定されていないため、getTitle()で取得できない。
メインシーンコンテナの場合は設定されている。

**Comment by simdy** [comment]
シーンコンテナは（"メイン"かどうかに関わらず）getTitle(), setTitle()を持ち、また、data-h5-title属性があり条件にマッチすればその属性値が当該シーンコンテナの「タイトル」として設定されるのが仕様です。
