### ISSUE TITLE
baloonプラグインを有効化してバルーンを表示させるたびにvalidation-baloonクラス要素が追加されてゆく

### ISSUE THREAD

**Issue by tom75s** [hifive/hifivemain#534]
validation-baloonクラス要素はバルーンを表示するときに生成されています。
バルーンを非表示にするタイミングでdisposeしていますが、追加した要素を削除していないことが原因のようです

**Comment by tom75s** [comment]
h5.ui.components.BaloonController#create() で不要なappend()が行われており、ここで追加されたvalidation-baloonクラス要素がdispose後にも残っています。

**Comment by simdy** [comment]
b0d0fea のコメントについて：「option.containerが指定されていればcontainerに、containerがなくoption.targetが指定されていればtargetの親要素（target.parentElement）に、containerもtargetも存在しなければdocument.bodyにappendします。」が正しいです。
