### ISSUE TITLE
jsBuild.jsをhifive-custom-build.jarに名称変更し、ivy.xmlのClosure Compilerを最新化する。

### ISSUE THREAD

**Issue by okabey** [hifive/hifivemain#572]
hifive-custom-buildプロジェクトのbuild.xmlが出力するjarファイルの名前をjsBuild.jsからhifive-custom-build.jarに変更したため、関連するプロジェクトが参照するjarファイルを更新する。
また、hifive-custom-build.jarが使用するClosure Compilerはrevをv20160619のため、ivy.xmlも更新する。

**Comment by simdy** [comment]
#533 と関連。
