### ISSUE TITLE
indicator の promises に jQuery の素の promise をひとつ渡すと resolve してもインジケータが解除されない

### ISSUE THREAD

**Issue by 3bch** [hifive/hifivemain#593]
`$.Deferred()` から作った promise をひとつだけ indicator の promises にわたすと、resolve してもインジケータが解除されません

配列で複数渡した場合や、 `h5.async.deferred()` で作成した promise を渡した場合は問題なく解除されます

確認した環境
* hifive: 1.2.2
* jQuery: 2.2.4

**Comment by 3bch** [comment]
調査の結果 `registerCallbacksSilently()` の `promise._h5UnwrappedCall ` が存在しなかった場合のコードが問題あることがわかりました。

`promise[method](args)` と呼び出されますが、`args` は配列になっており、正しく呼び出すためには `promise[method].apply(promise, args)` と呼び出す必要があります。

`args` が常に配列となるかは未確認のため、その辺を確認した上で修正する必要があります。

**Comment by 3bch** [comment]
> args が常に配列となるか

を調査した結果以下のようになっていました。

`createInterceptor()` の中で配列ではなくひとつの function が渡されている。
それ以外では配列を渡している。

対応策として以下の2つが考えられる。

* `args` が配列でなければ配列にくるんで `apply()` を呼び出す
* `args` が配列でなければ `promise[method](args)` と現行ままとし、配列であれば `apply()` を呼び出す

**Comment by simdy** [comment]
修正済み。
