### ISSUE TITLE
h5.ui.validation.Composition 入力項目の値が変更されたタイミングで更新したい

### ISSUE THREAD

**Issue by mtakeuchi** [hifive/hifivemain#594]
入力項目の横に表示されるバルーン(BootstrapErrorBalloon/ErrorBalloon)のように、入力要素に対するfocusin/focusout/change/clickイベントのタイミングで、Copositionで指定したエリアのエラーメッセージも動的に更新したい。

**Comment by simdy** [comment]
ver.1.3.2で追加。現時点のdevブランチで追加済み。
OutputプラグインのupdateOnのタイミングで設定を変更可能。
